In [98]:


import pandas as pd
from sklearn.model_selection import train_test_split                        # DataSet ko Training aur testing  data me divide karne ke liye..
from sklearn.preprocessing import StandardScaler , LabelEncoder             # feature ko standard scale par lane ke liye , taaki ANN/DL model efficiently train ho....
import pickle                                                               # Label encoder:-- Categorical text values ko numbers me convert karne ke liye...

0

# pickle :-- pickle file me predicted  model ko save krna.......

0

# FEATURE ENGINEERING

## CATEGORICAL FEATURES INTO NUMERICAL FEATURES .....
#### categorical features ko numerical features me convert kiya ...

In [99]:
# 1) Load the dataset...

data = pd.read_csv(r"C:\Users\harsh\OneDrive\Documents\Downloads\ANN CLASSIFICATION DEEPLEARNING PROJECT\Churn_Modelling.csv")

print(type(data))

<class 'pandas.DataFrame'>

In [100]:
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [101]:
# 2) Preprocessing the data....
### Drop irrelevant columns from the dataset...        # Geography and Gender are Categorical features ... 

data = data.drop(["RowNumber","CustomerId","Surname"], axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [102]:
# 3) Encode :-  Ek format se Dusre Format me change krna using LabelEncoder    # Label:-- matlab usko naam dena ...
# fit data se learn krta hain .. Transform convert karta hain ..   # labelencoder:-- spam ham ya text ko numerical (0,1) me convert karne ke liye...
# IMPPP

label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])       ## Female → 0  Male   → 1 
data
              # label encoder se male ko 1 aur female ko 0 me convert kar diya hain..   # ab ANN model efficiently train hoga...

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [103]:
## For The Geography Column we will use OneHotEncoding because it has more than 2 categories .....
# 
# Geography Column me 3 categories hain:
# France, Germany, Spain. Agar hum label 
# encoding use karenge to model ko ye samajh 
# nahi aayega ki France aur Germany me kya relation hain. 
# Isliye hum one hot encoding use karenge jisse ki model efficiently train hoga.

# ek sth 0 ,1 me nhi kar skte hain kyuki vo non linear ho jayega ...
# HUME geography Column ko values Assign karna hain .. france ko 0 , germany ko 1 aur spain ko 2 assign karna hain .. toh problem...



########### SUPER IMP INFO:--
# LABEL ENCODER:-- USE HOTA HAIN (0 , 1) ME CONVERT KARNE KE LIYE ..  # ONE HOT ENCODER:-- USE HOTA HAIN (0 , 1 , 2) ME CONVERT KARNE KE LIYE ...

In [104]:
## 4) Onehot encode  'Geography' ...         # if we arrange in 0 , 1 , 2  as france , spain , germany # 

from sklearn.preprocessing import OneHotEncoder 

onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
onehot_encoder_geo.get_feature_names_out(['Geography'])

geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [105]:
# ARRAY ME CONVERT KIYA.#10,000 records × 3 categories की One-Hot Encoded sparse matrix है, जिसमें 10,000 non-zero (1.0) values stored हैं।

geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [106]:
## CHECK KIYA ....

onehot_encoder_geo.get_feature_names_out(['Geography'])                  # features converted into p

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [107]:
## 5)Ye line encoded data ko ek proper Pandas DataFrame mein convert karti hai, aur uske columns ke naam bhi set karti hai.

geo_encoded_df = pd.DataFrame(geo_encoder.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

geo_encoded_df

                                  # ISko Dataframe me store kiya.....
# Using ONE HOT ENCODING00000

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [108]:
## 6)Combine One Hot Encoded Geography DataFrame with the original Data......

# CONCATENATE:-- 2 ya 2 se jyada dataframes ko combine karne ke liye use hota hain...

data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df ], axis=1)    # axis=1 means concatenate along columns
data.head()


# geography col ko remove aur geo_encoded_df ko add kar diya hain.

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [109]:

# from sklearn.feature_extraction.text import CountVectorizer          # FOR BOW ....

# bow = CountVectorizer()

# geo_encoder = bow.fit_transform(data['Geography'])

# print(bow.get_feature_names_out())
 
# print(geo_encoder.toarray())

In [110]:
## SAVE THE ENCODER AND SCALER  IN PICKLE FILES...
## LABEL ENCODER AUR ONE HOT ENCODER KO PICKLE FILE ME SAVE KARNE KE LIYE YE CODE HAIN...    SUPERRRR IMPPPPP




with open('label_encoder_gender.pkl', 'wb') as file:         # open a pickle file ....
    pickle.dump(label_encoder_gender, file)                  # dump kiya label_encoder_gender in file..
    
    
with open('onehot_encoder_geo.pkl', 'wb') as file:     # create or open ..
    pickle.dump(onehot_encoder_geo, file)               # dump kiya onehot_encoder_geo in file..

In [111]:
# DIVIDE THE DATASET INTO DEPENDENT AND INDEPENDENT FEATURES....   # Super imppp

# Exited is my dependent features..
# remaining are my independent features.. like geography_france, geography_germany, geography_spain, credit_score, gender

X = data.drop('Exited', axis=1)       # drop exited col..... baaki saare col ko X me store kro ....
y = data['Exited']                    # exited col ko y me store kro ....


## Split the dataset into training and testing sets ......

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)   # 20% data testing ke liye aur 80% data training ke liye use hoga..


## Scales these features   ... ## common features pe convert krna 

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)   # Training data par fit karke transform kiya
X_test = scaler.transform(X_test)

In [112]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 12))

In [113]:
# Save the scaler in a pickle file for future use....

with open('scaler.pkl', 'wb') as file:         # open a pickle file ....
    pickle.dump(scaler, file)                  # dump kiya scaler in file..

#  ANN IMPLEMENTATION

In [114]:
import tensorflow as tf

from tensorflow.keras.models import Sequential   
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping ,TensorBoard
import datetime    


 
# sequence me model  ko add krta hain ...
# Dense:-- fully connected layer  (node ).. use model learn krne ke liye .....
# callbacks:-- early stopping training ko rok deta hain jb model me improvement nahi hui  # agar model overfit ho raha hain toh training ko rok dega..
# TensorBoard:-- training ke process ko visualize karne ke liye use hota hain..

In [115]:
(X_train.shape[1])                                # 1 = columns , 0 = rows

12

## BUILD OUR ANN MODEL...

ANN IMPLEMENTATION ....

In [116]:
# ## 1)Build Our ANN Model ....

model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),  ## HL1  Connected with input layer...
    Dense(32, activation='relu'),   ## HL2
    Dense(1, activation='sigmoid')  ## output  layer Sigmoid (0,1) me 
]

)

c:\Users\harsh\miniconda3\envs\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [117]:
model.summary()                  # Total Parameters    # Combination of weights and biases in all layers.

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [118]:
import tensorflow 

# st 2

opt = tensorflow.keras.optimizers.Adam(learning_rate =0.01)        # # optimizers hain Adam .....

loss = tensorflow.keras.losses.BinaryCrossentropy()                 # loss kiya ..... binary
loss

In [119]:
## 3) COMPILE THE MODEL....... # SUPER IMP ...

model.compile(optimizer=opt, loss="binary_crossentropy", metrics=["accuracy"])          # loss ="binary_crossentropy"  # multiple classification = sparse_crossentropy....

### Still not Started the Training..

In [120]:
##  4) Setup the Tensorboard..... # Training ka data  log me store hoga(ex:- loss , accuracy).. DIRECTORY BANAI .....  # tensoboard ke jagah hum matplotlib....

from tensorflow.keras.callbacks import EarlyStopping ,TensorBoard

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")                             # jb model train hoga toh  aur analyse ke liye..
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)   # hist                  # TensorBoard visualize the log during Traning  model

In [121]:
## 5) Setup Early Stopping Callbacks..... # epochs ek baar train ... early stop isliye agar 20 epochs me accha kar rha toh 100 epoch ki jrurat nhi.

early_stoppping_callbacks = EarlyStopping( monitor = 'val_loss', patience =5 ,restore_best_weights=True)                # model rokne ke liye

### Train the Model ...

In [122]:
## Train the Model ..             # Model Train Ho Raha hain

history = model.fit(
    X_train , y_train ,validation_data =(X_test , y_test),epochs =100,
    callbacks = [tensorflow_callback , early_stoppping_callbacks] 
    
)

Epoch 1/100

250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8344 - loss: 0.3908 - val_accuracy: 0.8485 - val_loss: 0.3650
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8499 - loss: 0.3547 - val_accuracy: 0.8545 - val_loss: 0.3455
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8572 - loss: 0.3459 - val_accuracy: 0.8595 - val_loss: 0.3421
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8589 - loss: 0.3443 - val_accuracy: 0.8585 - val_loss: 0.3505
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8608 - loss: 0.3418 - val_accuracy: 0.8615 - val_loss: 0.3399
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8626 - loss: 0.3378 - val_accuracy: 0.8610 - val_loss: 0.3442
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8608 - loss: 0.3387 - val_accuracy: 0.8590 - val_loss: 0.3462
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8621 - loss: 0.3320 - val_accuracy: 0.8590 - val_loss: 0.3396
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8615 - loss: 0.3342 - val_accuracy: 0.8555 - val_loss: 0.3524
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8621 - loss: 0.3311 - val_accuracy: 0.8585 - val_loss: 0.3478
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8633 - loss: 0.3312 - val_accuracy: 0.8600 - val_loss: 0.3423
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8685 - loss: 0.3274 - val_accuracy: 0.8585 - val_loss: 0.3454
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8681 - loss: 0.3242 - val_accuracy: 0.8545 - val_loss: 0.3560

In [123]:
# val_loss = model ko data par check krne pr kitna loss 

# val_loss = model performance

In [124]:
# Save the trained model.......

model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [125]:
# load Tensorboard Extension...
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [126]:
# Tensorboard ...

%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 23228), started 8 days, 19:38:00 ago. (Use '!kill 23228' to kill it.)